[package]
name = "rsdu"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }

[lints]
workspace = true
