[package]
name = "rsdu"
version = "0.1.0"
edition = "2021"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
ncurses = "5.101.0"
librsdu = { path = "../src-lib" }

[lints]
workspace = true
